#!/usr/bin/env ruby
require "set"
sources = Dir[File.join(__dir__, '../docs/**/*.md')].map { |path| File.expand_path(path) }
            .to_set
config = File.read(File.join(__dir__, 'po4a.cfg'))
translated = config.scan(/^\[[^\]]+\] (\S+)/m).map do |path|
  path, = path
  File.expand_path(File.join(__dir__, path))
end.to_set
diff = sources - translated
pp diff
